module.exports={
    getLinkSuccess:{
        code:0,
        message:'获取链接成功',
        result:null
    },
    loginSuccess:{
        code:0,
        message:'登陆成功',
        result:null
    },
    logoutSuccess:{
        code:0,
        message:'登出成功',
        result:null
    },
    sendCaptchaSuccess:{
        code:0,
        message:'发送验证码成功',
        result:null
    },
    queryNoticeSuccess:{
        code:0,
        message:'查询用户须知成功',
        result:null
    },
    reviseNoticeSuccess:{
        code:0,
        message:'更新用户须知成功',
        result:null
    }
    ,
    queryPublicNoticeSuccess:{
        code:0,
        message:'查询公告成功',
        result:null
    },
    revisePublicNoticeSuccess:{
        code:0,
        message:'修改公告成功',
        result:null
    },
    createUserSuccess:{
        code:0,
        message:'创建用户成功',
        result:null
    },
    queryUsersSuccess:{
        code:0,
        message:'查询用户成功',
        result:null 
    },
    deleteUserSuccess:{
        code:0,
        message:'删除用户成功',
        result:null 
    },
    updateUserSuccess:{
        code:0,
        message:'更新用户成功',
        result:null 
    },
    wxBindSuccess:{
        code:0,
        message:'绑定微信成功',
        result:null 
    },
    queryUserSelfSuccess:{
        code:0,
        message:'查询用户自身信息成功',
        result:null 
    }
}